apiVersion: v1
kind: Secret
metadata:
  name: fleet-health-api-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  FLEETPULSE_MLFLOW_TRACKING_TOKEN: {{ .Values.mlflowTrackingToken | quote }}
